repos = {
    'snipsco': 'snips-nlu',
    'tensorlayer': 'tensorlayer',
    'secdev': 'scapy',
    'keras-team': 'keras',
    'dask': 'dask',
    'gunthercox': 'ChatterBot',
    'explosion': 'spaCy',
    'giampaolo': 'psutil',
    'ethereum': 'pyethereum',
    'pyca': 'cryptography',
    'docker': 'docker-py',
    'HypothesisWorks': 'hypothesis',
    'spulec': 'moto',
    'dedupeio': 'dedupe',
    'bokeh': 'bokeh',
    'Theano': 'Theano',
    'scikit-image': 'scikit-image',
    'scipy': 'scipy',
    'matplotlib': 'matplotlib',
    'requests': 'requests',
    'RaRe-Technologies': 'gensim',
    'gitpython-developers': 'GitPython',
    'pandas-dev': 'pandas',
    'scikit-learn': 'scikit-learn',
    'sympy': 'sympy',
    'pika': 'pika',
    }